server:
  port: 9002

dubbo:
  application:
    name: OrderService
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: zookeeper://101.37.152.54:2183

spring:
  output:
  ansi:
  enabled: always
