server:
  port: 8001

dubbo:
  application:
    ##### 注册服务的名称
    name: DemoRest
  ##### 注册中心地址
  registry:
    address: zookeeper://101.37.152.54:2183
  ##### 调用服务超时时间
  consumer:
    timeout: 5000
    loadbalance: roundrobin


spring:
  output:
    ansi:
      enabled: always
