server:
  port: 9002

dubbo:
  application:
    name: DemoProvider
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: nacos://190.1.1.77:8848

spring:
  output:
  ansi:
  enabled: always