server:
  port: 8001

dubbo:
  application:
    ##### 注册服务的名称
    name: DemoRest
  ##### 注册中心地址
  registry:
    address: zookeeper://localhost:2181
  ##### 调用服务超时时间
  consumer:
    timeout: 5000

spring:
  output:
    ansi:
      enabled: always

logging:
  level:
    root: info
    com.netflix.hystrix.strategy.properties.HystrixPropertiesChainedProperty: info